import type { AudioOutputs, ChannelMixFilter, EQBand } from '../types/Filters'
import type { NodeLinkEventTypes } from '../types/NodeLink'

export enum DebugEvents {
  SetSponsorBlock = 'SetSponsorBlock',
  DeleteSponsorBlock = 'DeleteSponsorBlock',
  TrackEndReplaced = 'TrackEndReplaced',

  AutoplayExecution = 'AutoplayExecution',
  AutoplayNoSongsAdded = 'AutoplayNoSongsAdded',
  AutoplayThresholdSpamLimiter = 'AutoplayThresholdSpamLimiter',
  TriggerQueueEmptyInterval = 'TriggerQueueEmptyInterval',
  QueueEnded = 'QueueEnded',
  TrackStartNewSongsOnly = 'TrackStartNewSongsOnly',
  TrackStartNoTrack = 'TrackStartNoTrack',

  ResumingFetchingError = 'ResumingFetchingError',

  PlayerUpdateNoPlayer = 'PlayerUpdateNoPlayer',
  PlayerUpdateFilterFixApply = 'PlayerUpdateFilterFixApply',
  PlayerUpdateSuccess = 'PlayerUpdateSuccess',

  HeartBeatTriggered = 'HeartBeatTriggered',
  NoSocketOnDestroy = 'NoSocketOnDestroy',
  SocketCleanupError = 'SocketCleanupError',
  SocketTerminateHeartBeatTimeout = 'SocketTerminateHeartBeatTimeout',

  TryingConnectWhileConnected = 'TryingConnectWhileConnected',

  SearchNothingFound = 'SearchNothingFound',

  ValidatingBlacklistLinks = 'ValidatingBlacklistLinks',
  ValidatingWhitelistLinks = 'ValidatingWhitelistLinks',

  TrackErrorMaxTracksErroredPerTime = 'TrackErrorMaxTracksErroredPerTime',
  TrackStuckMaxTracksErroredPerTime = 'TrackStuckMaxTracksErroredPerTime',

  PlayerDestroyingSomewhereElse = 'PlayerDestroyingSomewhereElse',
  PlayerCreateNodeNotFound = 'PlayerCreateNodeNotFound',
  PlayerPlayQueueEmptyTimeoutClear = 'PlayerPlayQueueEmptyTimeoutClear',
  PlayerPlayWithTrackReplace = 'PlayerPlayWithTrackReplace',
  PlayerPlayUnresolvedTrack = 'PlayerPlayUnresolvedTrack',
  PlayerPlayUnresolvedTrackFailed = 'PlayerPlayUnresolvedTrackFailed',
  PlayerVolumeAsFilter = 'PlayerVolumeAsFilter',
  BandcampSearchLokalEngine = 'BandcampSearchLokalEngine',
  PlayerChangeNode = 'PlayerChangeNode',

  BuildTrackError = 'BuildTrackError',
  TransformRequesterFunctionFailed = 'TransformRequesterFunctionFailed',
  GetClosestTrackFailed = 'GetClosestTrackFailed',
  PlayerDeleteInsteadOfDestroy = 'PlayerDeleteInsteadOfDestroy',
  FailedToConnectToNodes = 'FailedToConnectToNodes',
  NoAudioDebug = 'NoAudioDebug',
  PlayerAutoReconnect = 'PlayerAutoReconnect',

  PlayerDestroyFail = 'PlayerDestroyFail',
  PlayerChangeNodeFailNoEligibleNode = 'PlayerChangeNodeFailNoEligibleNode',
  PlayerChangeNodeFail = 'PlayerChangeNodeFail',

  NodeConnectSuccess = 'NodeConnectSuccess',
  NodeConnectFail = 'NodeConnectFail',
  NodeReconnectAttempt = 'NodeReconnectAttempt',
  NodeReconnectSuccess = 'NodeReconnectSuccess',
  NodeReconnectFail = 'NodeReconnectFail',
  NodeHandshakeSync = 'NodeHandshakeSync',
  NodeDisconnect = 'NodeDisconnect',
  NodeDestroy = 'NodeDestroy',
  NodeRawMessage = 'NodeRawMessage',
  NodeRawEvent = 'NodeRawEvent',
  NodeStatsUpdate = 'NodeStatsUpdate',
  NodeAtomicMigration = 'NodeAtomicMigration',
}

export enum DestroyReasons {
  QueueEmpty = 'QueueEmpty',
  NodeDestroy = 'NodeDestroy',
  NodeDeleted = 'NodeDeleted',
  NodeNoVoice = 'NodeNoVoice',
  NodeReconnectFail = 'NodeReconnectFail',
  Disconnected = 'Disconnected',
  PlayerReconnectFail = 'PlayerReconnectFail',
  PlayerChangeNodeFail = 'PlayerChangeNodeFail',
  PlayerChangeNodeFailNoEligibleNode = 'PlayerChangeNodeFailNoEligibleNode',
  ChannelDeleted = 'ChannelDeleted',
  DisconnectAllNodes = 'DisconnectAllNodes',
  ReconnectAllNodes = 'ReconnectAllNodes',
  TrackErrorMaxTracksErroredPerTime = 'TrackErrorMaxTracksErroredPerTime',
  TrackStuckMaxTracksErroredPerTime = 'TrackStuckMaxTracksErroredPerTime',
}

export enum DisconnectReasons {
  Disconnected = 'Disconnected',
  DisconnectAllNodes = 'DisconnectAllNodes',
}

export const validSponsorBlocks = ['sponsor', 'selfpromo', 'interaction', 'intro', 'outro', 'preview', 'music_offtopic', 'filler']

export const audioOutputsData: Record<AudioOutputs, ChannelMixFilter> = {
  mono: {
    leftToLeft: 0.5,
    leftToRight: 0.5,
    rightToLeft: 0.5,
    rightToRight: 0.5,
  },
  stereo: {
    leftToLeft: 1,
    leftToRight: 0,
    rightToLeft: 0,
    rightToRight: 1,
  },
  left: {
    leftToLeft: 1,
    leftToRight: 0,
    rightToLeft: 1,
    rightToRight: 0,
  },
  right: {
    leftToLeft: 0,
    leftToRight: 1,
    rightToLeft: 0,
    rightToRight: 1,
  },
}

export const EQList = {
  BassboostEarrape: [
    { band: 0, gain: 0.6 * 0.375 },
    { band: 1, gain: 0.67 * 0.375 },
    { band: 2, gain: 0.67 * 0.375 },
    { band: 3, gain: 0.4 * 0.375 },
    { band: 4, gain: -0.5 * 0.375 },
    { band: 5, gain: 0.15 * 0.375 },
    { band: 6, gain: -0.45 * 0.375 },
    { band: 7, gain: 0.23 * 0.375 },
    { band: 8, gain: 0.35 * 0.375 },
    { band: 9, gain: 0.45 * 0.375 },
    { band: 10, gain: 0.55 * 0.375 },
    { band: 11, gain: -0.6 * 0.375 },
    { band: 12, gain: 0.55 * 0.375 },
    { band: 13, gain: -0.5 * 0.375 },
    { band: 14, gain: -0.75 * 0.375 },
  ] as EQBand[],

  BassboostHigh: [
    { band: 0, gain: 0.6 * 0.25 },
    { band: 1, gain: 0.67 * 0.25 },
    { band: 2, gain: 0.67 * 0.25 },
    { band: 3, gain: 0.4 * 0.25 },
    { band: 4, gain: -0.5 * 0.25 },
    { band: 5, gain: 0.15 * 0.25 },
    { band: 6, gain: -0.45 * 0.25 },
    { band: 7, gain: 0.23 * 0.25 },
    { band: 8, gain: 0.35 * 0.25 },
    { band: 9, gain: 0.45 * 0.25 },
    { band: 10, gain: 0.55 * 0.25 },
    { band: 11, gain: -0.6 * 0.25 },
    { band: 12, gain: 0.55 * 0.25 },
    { band: 13, gain: -0.5 * 0.25 },
    { band: 14, gain: -0.75 * 0.25 },
  ] as EQBand[],

  BassboostMedium: [
    { band: 0, gain: 0.6 * 0.1875 },
    { band: 1, gain: 0.67 * 0.1875 },
    { band: 2, gain: 0.67 * 0.1875 },
    { band: 3, gain: 0.4 * 0.1875 },
    { band: 4, gain: -0.5 * 0.1875 },
    { band: 5, gain: 0.15 * 0.1875 },
    { band: 6, gain: -0.45 * 0.1875 },
    { band: 7, gain: 0.23 * 0.1875 },
    { band: 8, gain: 0.35 * 0.1875 },
    { band: 9, gain: 0.45 * 0.1875 },
    { band: 10, gain: 0.55 * 0.1875 },
    { band: 11, gain: -0.6 * 0.1875 },
    { band: 12, gain: 0.55 * 0.1875 },
    { band: 13, gain: -0.5 * 0.1875 },
    { band: 14, gain: -0.75 * 0.1875 },
  ] as EQBand[],

  BassboostLow: [
    { band: 0, gain: 0.6 * 0.125 },
    { band: 1, gain: 0.67 * 0.125 },
    { band: 2, gain: 0.67 * 0.125 },
    { band: 3, gain: 0.4 * 0.125 },
    { band: 4, gain: -0.5 * 0.125 },
    { band: 5, gain: 0.15 * 0.125 },
    { band: 6, gain: -0.45 * 0.125 },
    { band: 7, gain: 0.23 * 0.125 },
    { band: 8, gain: 0.35 * 0.125 },
    { band: 9, gain: 0.45 * 0.125 },
    { band: 10, gain: 0.55 * 0.125 },
    { band: 11, gain: -0.6 * 0.125 },
    { band: 12, gain: 0.55 * 0.125 },
    { band: 13, gain: -0.5 * 0.125 },
    { band: 14, gain: -0.75 * 0.125 },
  ] as EQBand[],

  BetterMusic: [
    { band: 0, gain: 0.25 },
    { band: 1, gain: 0.025 },
    { band: 2, gain: 0.0125 },
    { band: 3, gain: 0 },
    { band: 4, gain: 0 },
    { band: 5, gain: -0.0125 },
    { band: 6, gain: -0.025 },
    { band: 7, gain: -0.0175 },
    { band: 8, gain: 0 },
    { band: 9, gain: 0 },
    { band: 10, gain: 0.0125 },
    { band: 11, gain: 0.025 },
    { band: 12, gain: 0.25 },
    { band: 13, gain: 0.125 },
    { band: 14, gain: 0.125 },
  ] as EQBand[],

  Rock: [
    { band: 0, gain: 0.3 },
    { band: 1, gain: 0.25 },
    { band: 2, gain: 0.2 },
    { band: 3, gain: 0.1 },
    { band: 4, gain: 0.05 },
    { band: 5, gain: -0.05 },
    { band: 6, gain: -0.15 },
    { band: 7, gain: -0.2 },
    { band: 8, gain: -0.1 },
    { band: 9, gain: -0.05 },
    { band: 10, gain: 0.05 },
    { band: 11, gain: 0.1 },
    { band: 12, gain: 0.2 },
    { band: 13, gain: 0.25 },
    { band: 14, gain: 0.3 },
  ] as EQBand[],

  Classic: [
    { band: 0, gain: 0.375 },
    { band: 1, gain: 0.35 },
    { band: 2, gain: 0.125 },
    { band: 3, gain: 0 },
    { band: 4, gain: 0 },
    { band: 5, gain: 0.125 },
    { band: 6, gain: 0.55 },
    { band: 7, gain: 0.05 },
    { band: 8, gain: 0.125 },
    { band: 9, gain: 0.25 },
    { band: 10, gain: 0.2 },
    { band: 11, gain: 0.25 },
    { band: 12, gain: 0.3 },
    { band: 13, gain: 0.25 },
    { band: 14, gain: 0.3 },
  ] as EQBand[],

  Pop: [
    { band: 0, gain: 0.2635 },
    { band: 1, gain: 0.22141 },
    { band: 2, gain: -0.21141 },
    { band: 3, gain: -0.1851 },
    { band: 4, gain: -0.155 },
    { band: 5, gain: 0.21141 },
    { band: 6, gain: 0.22456 },
    { band: 7, gain: 0.237 },
    { band: 8, gain: 0.237 },
    { band: 9, gain: 0.237 },
    { band: 10, gain: -0.05 },
    { band: 11, gain: -0.116 },
    { band: 12, gain: 0.192 },
    { band: 13, gain: 0 },
    { band: 14, gain: 0 },
  ] as EQBand[],

  Electronic: [
    { band: 0, gain: 0.375 },
    { band: 1, gain: 0.35 },
    { band: 2, gain: 0.125 },
    { band: 3, gain: 0 },
    { band: 4, gain: 0 },
    { band: 5, gain: -0.125 },
    { band: 6, gain: -0.125 },
    { band: 7, gain: 0 },
    { band: 8, gain: 0.25 },
    { band: 9, gain: 0.125 },
    { band: 10, gain: 0.15 },
    { band: 11, gain: 0.2 },
    { band: 12, gain: 0.25 },
    { band: 13, gain: 0.35 },
    { band: 14, gain: 0.4 },
  ] as EQBand[],

  FullSound: [
    { band: 0, gain: 0.25 + 0.375 },
    { band: 1, gain: 0.25 + 0.025 },
    { band: 2, gain: 0.25 + 0.0125 },
    { band: 3, gain: 0.25 + 0 },
    { band: 4, gain: 0.25 + 0 },
    { band: 5, gain: 0.25 + -0.0125 },
    { band: 6, gain: 0.25 + -0.025 },
    { band: 7, gain: 0.25 + -0.0175 },
    { band: 8, gain: 0.25 + 0 },
    { band: 9, gain: 0.25 + 0 },
    { band: 10, gain: 0.25 + 0.0125 },
    { band: 11, gain: 0.25 + 0.025 },
    { band: 12, gain: 0.25 + 0.375 },
    { band: 13, gain: 0.25 + 0.125 },
    { band: 14, gain: 0.25 + 0.125 },
  ] as EQBand[],

  Gaming: [
    { band: 0, gain: 0.35 },
    { band: 1, gain: 0.3 },
    { band: 2, gain: 0.25 },
    { band: 3, gain: 0.2 },
    { band: 4, gain: 0.15 },
    { band: 5, gain: 0.1 },
    { band: 6, gain: 0.05 },
    { band: 7, gain: -0.0 },
    { band: 8, gain: -0.05 },
    { band: 9, gain: -0.1 },
    { band: 10, gain: -0.15 },
    { band: 11, gain: -0.2 },
    { band: 12, gain: -0.25 },
    { band: 13, gain: -0.3 },
    { band: 14, gain: -0.35 },
  ] as EQBand[],

  BassBoost: [
    { band: 0, gain: 0.6 },
    { band: 1, gain: 0.7 },
    { band: 2, gain: 0.8 },
    { band: 3, gain: 0.55 },
    { band: 4, gain: 0.35 },
    { band: 5, gain: 0.2 },
    { band: 6, gain: 0.1 },
    { band: 7, gain: 0 },
    { band: 8, gain: 0 },
    { band: 9, gain: 0 },
    { band: 10, gain: 0 },
    { band: 11, gain: 0 },
    { band: 12, gain: 0 },
    { band: 13, gain: 0 },
    { band: 14, gain: 0 },
  ] as EQBand[],

  Soft: [
    { band: 0, gain: 0 },
    { band: 1, gain: 0 },
    { band: 2, gain: 0 },
    { band: 3, gain: 0 },
    { band: 4, gain: 0 },
    { band: 5, gain: 0 },
    { band: 6, gain: 0 },
    { band: 7, gain: 0 },
    { band: 8, gain: -0.25 },
    { band: 9, gain: -0.25 },
    { band: 10, gain: -0.25 },
    { band: 11, gain: -0.25 },
    { band: 12, gain: -0.25 },
    { band: 13, gain: -0.25 },
    { band: 14, gain: -0.25 },
  ] as EQBand[],

  TV: [
    { band: 0, gain: 0 },
    { band: 1, gain: 0 },
    { band: 2, gain: 0 },
    { band: 3, gain: 0.1 },
    { band: 4, gain: 0.15 },
    { band: 5, gain: 0.2 },
    { band: 6, gain: 0.25 },
    { band: 7, gain: 0.2 },
    { band: 8, gain: 0.15 },
    { band: 9, gain: 0 },
    { band: 10, gain: 0 },
    { band: 11, gain: 0 },
    { band: 12, gain: 0 },
    { band: 13, gain: 0 },
    { band: 14, gain: 0 },
  ] as EQBand[],

  Radio: [
    { band: 0, gain: -0.25 },
    { band: 1, gain: -0.25 },
    { band: 2, gain: -0.25 },
    { band: 3, gain: -0.1 },
    { band: 4, gain: 0.05 },
    { band: 5, gain: 0.1 },
    { band: 6, gain: 0.2 },
    { band: 7, gain: 0.1 },
    { band: 8, gain: 0.05 },
    { band: 9, gain: -0.1 },
    { band: 10, gain: -0.25 },
    { band: 11, gain: -0.25 },
    { band: 12, gain: -0.25 },
    { band: 13, gain: -0.25 },
    { band: 14, gain: -0.25 },
  ] as EQBand[],

  Lofi: [
    { band: 0, gain: 0.25 },
    { band: 1, gain: 0.2 },
    { band: 2, gain: -0.1 },
    { band: 3, gain: -0.2 },
    { band: 4, gain: -0.05 },
    { band: 5, gain: 0.1 },
    { band: 6, gain: 0.1 },
    { band: 7, gain: 0.05 },
    { band: 8, gain: -0.15 },
    { band: 9, gain: -0.2 },
    { band: 10, gain: -0.25 },
    { band: 11, gain: -0.15 },
    { band: 12, gain: 0.1 },
    { band: 13, gain: 0.15 },
    { band: 14, gain: 0.2 },
  ] as EQBand[],

  TrebleBass: [
    { band: 0, gain: 0.6 },
    { band: 1, gain: 0.5 },
    { band: 2, gain: 0.2 },
    { band: 3, gain: 0.1 },
    { band: 4, gain: 0 },
    { band: 5, gain: 0 },
    { band: 6, gain: 0 },
    { band: 7, gain: 0 },
    { band: 8, gain: 0 },
    { band: 9, gain: 0 },
    { band: 10, gain: 0 },
    { band: 11, gain: 0.1 },
    { band: 12, gain: 0.2 },
    { band: 13, gain: 0.45 },
    { band: 14, gain: 0.6 },
  ] as EQBand[],
}

export const RecommendationsStrings = {
  highCPULoad: (cpuLoad: number) => `High CPU load (${(cpuLoad * 100).toFixed(1)}%). Consider reducing player count or upgrading CPU.`,
  highSystemLoad: (systemLoad: number) => `High system load (${(systemLoad * 100).toFixed(1)}%). Check other processes on the server.`,
  highMemoryUsage: (memoryUsagePercent: number) =>
    `High memory usage (${memoryUsagePercent.toFixed(1)}%). Consider increasing allocated memory or reducing player count.`,
  frameDeficit: (frameDeficit: number) => `Frame deficit detected (${frameDeficit}). Audio quality may be affected. Check network and CPU.`,
  highLatency: (ping: number) => `High latency (${ping}ms). Check network connection to the node.`,
  nodeRestart: 'Node restart recommended to clear memory and reset connections.',
  highPlayercount: (players: number) => `High player count (${players}). Consider load balancing across multiple nodes.`,
  nodeOffline: 'Node is offline or disconnected',
  checkConnectivity: 'Check node connectivity and restart if needed',
}

export const NodeLinkExclusiveEvents: NodeLinkEventTypes[] = [
  'PlayerCreatedEvent',
  'PlayerDestroyedEvent',
  'PlayerConnectedEvent',
  'PlayerReconnectingEvent',
  'VolumeChangedEvent',
  'FiltersChangedEvent',
  'SeekEvent',
  'PauseEvent',
  'ConnectionStatusEvent',
  'MixStartedEvent',
  'MixEndedEvent',
  'LyricsFoundEvent',
  'LyricsLineEvent',
  'LyricsNotFoundEvent',
  'WorkerFailedEvent',
  'StreamMetadataEvent',
  'EternalBoxInfoEvent',
  'EternalBoxJumpEvent',
]
