name: Docs

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'ryanwtf7/ryanlink'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun.js
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies and build
        run: bun install

      - name: Install, build, and upload your site
        uses: withastro/action@v3
        with:
          path: ./docs
          package-manager: bun
          node-version: '22'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
